Shop/MyShop/urls.py
from django.urls import path

from . import views
app_name = 'MyShop'
urlpatterns = [
    path('', views.ProductView.as_view(), name='product_list'),
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('<slug:category_slug>/', views.ProductView.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.ProductDetail.as_view(), name='product_detail'),


]

Shop/Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('MyShop.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id/>', views.cart_remove, name='cart_remove'),

]

Shop/MyShop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Категория')
    slug = models.SlugField(max_length=200, unique=True, null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('MyShop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Товар')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    description = models.CharField(max_length=1000, verbose_name='Описание')
    image = models.ImageField(verbose_name='Картинка', upload_to='image/', default='default.jpg')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    slug = models.SlugField(max_length=200, unique=True, null=True)

    class Meta:
        ordering = ('category',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('MyShop:product_detail', args=[self.id, self.slug])


class Commentary(models.Model):
    name = models.CharField(max_length=500, verbose_name='Комментарий', null=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Товар', related_name='comment')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Пользователь', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.name

Shop/cart/models.py
from django.db import models

# Create your models here.

Shop/MyShop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Commentary


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class CommentForm(forms.ModelForm):
    class Meta:
        model = Commentary
        fields = ('name',)

Shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICE = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICE, coerce=int)
    update = forms.BooleanField(required=False, initial=False,widget=forms.HiddenInput)

Shop/MyShop/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import View, ListView, DetailView, CreateView, FormView, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from .forms import UserCreateForm, CommentForm
from Shop.cart.forms import CartAddProductForm


class ProductView(View):
    def get(self, request, category_slug=None):
        product = Product.objects.all()
        category = None
        categories = Category.objects.all()
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            product = product.filter(category=category)

        return render(request, 'product/list.html',
                      {'product_list': product, 'category': category, 'categories': categories,
                       'title': 'Главная страница'})


class ProductDetail(DetailView):
    def get(self, request, id, slug):
        prod = get_object_or_404(Product, id=id, slug=slug)
        comments = prod.comment.all()
        cart_product_form = CartAddProductForm()

        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.product = prod
                form.save()
                return redirect('product_detail', slug)
        else:

            form = CommentForm()

        return render(request, 'product/detail.html',
                      {'product': prod, 'comments': comments, 'form': form, 'cart_product_form': cart_product_form})


class RegisterFormView(FormView):
    form_class = UserCreateForm
    success_url = '/login/'
    template_name = 'product/register.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(RegisterFormView,self).form_invalid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = 'product/login.html'
    success_url = '/'

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class SearchResultsView(ListView):
    model = Product
    template_name = 'product/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(Q(name__icontains=query))
        return object_list

Shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Shop.MyShop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

Shop/MyShop/templates/product/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой первый магазин{% endblock %}</title>
    <link href="{% static 'myshop/css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
<a href="/" class="logo">Мой первый магазин</a>
</div>
<div id="subheader" >
    <form action="{% url 'MyShop:search_results' %}" method="get">
        <input name="q" type="text" placeholder="Поиск...">
    </form>
    <div style="text-align: right">
        {% if user.is_authenticated %}
        <a href="logout/">Выйти({{user.username}})</a>
        {% else %}
        <a href="register/">Регистрация</a> | <a href="login/">Войти</a>
        {% endif %}
    </div>
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

Shop/MyShop/templates/product/detail.html
{% extends "product/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">{{ product.price }} грн.</p>

{{ product.description|linebreaks }} <hr>
<form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзину">
</form>

</div>
<div>
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} комментарий {{ total_comments|pluralize }}
    </h2>
    {% endwith %}
    {% for comment in comments %}
    <div>
        <p>
            Комментарий {{ forloop.counter }} от {{ comment.name }}{{ comment.date }}
        </p>

    </div>
    {% empty %}
    <p>Нет комментариев</p>
    {% endfor %}

</div>
<div>
<a href="/">На главную страницу</a>
</div>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
{% endblock %}

Shop/MyShop/templates/product/list.html
{% extends 'product/base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>Категория</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url "MyShop:product_list" %}">Все</a>
        </li>
        {% for cat in categories %}
        <li {% if category.slug == cat.slug %}class="selected" {% endif %}>
            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    {% for p in product_list %}
    <div class="item">
        <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{{ p.get_absolute_url }}">{{ p.name }}</a>
        <br>
        {{ p.price }} грн.
    </div>
    {% endfor %}
</div>
{% endblock %}

Shop/MyShop/templates/product/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <label for="">{{field.label}}</label>
        <div>{{field}}</div>
        {% if field.errors %}
        <p>{{field.errors}}</p>
        {% endif %}
        {% endfor %}
        <button type="submit">Войти</button>
    </form>

</body>
</html>

Shop/MyShop/templates/product/old/about.html
{% extends 'women/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Содержимое страницы о сайте
{% endblock %}

Shop/MyShop/templates/product/old/base.html
{% load static %}
<!DOCTYPE html>
<html xmlns:MyShop="http://www.w3.org/1999/xhtml">
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'myshop/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'myshop/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="#"><div class="logo"></div></a></li>
{% for m in menu %}
	{% if not forloop.last %}
			<li><a href="#">{{m.title}}</a></li>
	{% else %}
			<li class="last"><a href="#">{{m.title}}</a></li>
	{% endif %}
{% endfor %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		<li {% if not category %}class="selected"{% endif %}>
            <a href="{% url "MyShop:product_list" %}">Все</a>
        </li>
        {% for cat in categories %}
        <li {% if category.slug == cat.slug %}class="selected"{% endif %}>
            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
        {% endfor %}

		<li class="share">
		</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td>


<!-- Блок контента -->
	<div>
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>

Shop/MyShop/templates/product/old/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'myshop/css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
{% block mainmenu %}
<ul>
  {% for m in menu %}
<li>{{ m }}</li>
   {% endfor %}
</ul>
{% endblock mainmenu %}

{% block content %}
{% endblock content %}
</body>
</html>

Shop/MyShop/templates/product/old/base_work.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'myshop/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'myshop/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="#"><div class="logo"></div></a></li>
{% for m in menu %}
	{% if not forloop.last %}
			<li><a href="#">{{m.title}}</a></li>
	{% else %}
			<li class="last"><a href="#">{{m.title}}</a></li>
	{% endif %}
{% endfor %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		<li class="selected">Все категории</li>
		<li><a href="#">Электрочайники</a></li>
		<li><a href="#">Блендеры</a></li>
		<li><a href="#">Микроволновые печи</a></li>
		<li class="share">
		</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>

Shop/MyShop/templates/product/old/index.html
{% extends 'product/base.html' %}

{% block content %}
<div class="test2">
	{% for p in product_list %}
			<h2>{{p.name}}</h2>
				<img src="{{ p.image.url }}"width="80" height="60" >
	{% autoescape on %}
	{{p.description|linebreaks|truncatewords:20}}
	{% endautoescape %}
			<h3>Цена {{ p.price }} грн.</h3>
			<div class="clear"></div>
			<p class="link-read-post"><a href="#">Полное описание</a></p>

	{% endfor %}
</div>
{% endblock %}

Shop/MyShop/templates/product/old/product_list.html
{% extends 'product/base.html' %}

{% block content %}

<ul>


    {% for product in product_list %}
    <li>
        <h2>{{ product.name }}</h2>
        <p>{{ product.description }}</p>
        <p>{{ product.price }} грн.</p>
        <hr>
    </li>
    {% endfor %}
</ul>
{% endblock %}

Shop/MyShop/templates/product/old/registerX.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>


    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
    </form>
</body>
</html>

Shop/MyShop/templates/product/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>


    <form action="" method="post">{% csrf_token %}
        {% for field in form %}
        <label for="">{{field.label}}</label>
        <div>{{field}}</div>
        {% if field.errors %}
        <p>{{field.errors}}</p>
        {% endif %}
        {% endfor %}
    <button type="submit">Зарегистрироваться</button>
    </form>
</body>
</html>

Shop/MyShop/templates/product/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результаты поиска</title>
</head>
<body>
<h1>Результаты поиска</h1>
  <ul>
    {% for product in object_list %}
      <li>
        <a href="{{ product.get_absolute_url }}">{{product.name}}</a>
      </li>
    {% endfor %}
  </ul>
<div>
    <a href="/">На главную</a>
</div>
</body>
</html>

Shop/cart/templates/cart/detail.html
{% extends 'MyShop/base.html' %}
{% load static %}
{% block titel %}
Ваша корзина
{% endblock %}
{% block content %}
    <h1>Ваша корзина</h1>
    <table>
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    {% for items in cart %}
        {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image.url %}
                            {{ product.image.url }}
                            {% else %}
                                {% static 'images/no_image.png' %}
                            {% endif %}">
                    </a>
                </td>
            <td>{{ product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a> </td>
            <td class="num">{{ item.price }} грн.</td>
            <td class="num">{{ item.total_price }} грн.</td>
            </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }} грн.</td>
    </tr>
    </tbody>
    </table>
    <p class="text-right">
    <a href="{% url 'MyShop:product_list' %}" class="button light">Продолжить покупки</a>
    <a href="#" class="button">Выход</a>
    </p>
{% endblock %}

{% endblock %}